<?php

namespace Boombit;

class Acf_Loader
{
    public static function load_options_page()
    {
        if (function_exists('acf_add_options_page')) {
            acf_add_options_page(array(
                'page_title' => 'Theme Options',
                'menu_title' => 'Theme Options',
                'menu_slug' => 'theme-options',
                'capability' => 'edit_posts',
                'redirect' => false
            ));
        }
    }

    public static function load_field_groups()
    {
        if (function_exists('acf_add_local_field_group')) {
            acf_add_local_field_group(array(
                'key' => 'group_6432f42330117',
                'title' => 'Block: All Conferences',
                'fields' => array(
                    array(
                        'key' => 'field_64332ffba3180',
                        'label' => 'Layout',
                        'name' => 'layout',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'one_cols' => 'One col',
                            'two_cols' => 'Two cols',
                        ),
                        'default_value' => false,
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_643331b4eee7e',
                        'label' => 'Text color',
                        'name' => 'text_color',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'primary' => 'Theme primary',
                            'primary-dark' => 'Theme primary dark',
                            'primary-darker' => 'Theme primary darker',
                            'secondary' => 'Theme secondary',
                            'success' => 'Success',
                            'info' => 'Info',
                            'warning' => 'Warning',
                            'danger' => 'Fanger',
                            'light' => 'Light',
                            'dark' => 'Dark',
                        ),
                        'default_value' => 'primary',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_64333a4cbf98f',
                        'label' => 'Title text color',
                        'name' => 'title_color',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'primary' => 'Theme primary',
                            'primary-dark' => 'Theme primary dark',
                            'primary-darker' => 'Theme primary darker',
                            'secondary' => 'Theme secondary',
                            'success' => 'Success',
                            'info' => 'Info',
                            'warning' => 'Warning',
                            'danger' => 'Fanger',
                            'light' => 'Light',
                            'dark' => 'Dark',
                        ),
                        'default_value' => 'primary',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_6433305da3181',
                        'label' => 'Conference row background color',
                        'name' => 'conference_row_background_color',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'primary' => 'Theme primary',
                            'primary-dark' => 'Theme primary dark',
                            'primary-darker' => 'Theme primary darker',
                            'secondary' => 'Theme secondary',
                            'success' => 'Success',
                            'info' => 'Info',
                            'warning' => 'Warning',
                            'danger' => 'Fanger',
                            'light' => 'Light',
                            'dark' => 'Dark',
                        ),
                        'default_value' => 'primary',
                        'return_format' => '',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_6433430e1e1be',
                        'label' => 'Conference row margin',
                        'name' => 'conference_row_margin',
                        'aria-label' => '',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 2,
                        'min' => 0,
                        'max' => 4,
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6433438898b53',
                        'label' => 'Conference row padding',
                        'name' => 'conference_row_padding',
                        'aria-label' => '',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 2,
                        'min' => 0,
                        'max' => 4,
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_64334d549d405',
                        'label' => 'Text column background color',
                        'name' => 'text_column_background_color',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'primary' => 'Theme primary',
                            'primary-dark' => 'Theme primary dark',
                            'primary-darker' => 'Theme primary darker',
                            'secondary' => 'Theme secondary',
                            'success' => 'Success',
                            'info' => 'Info',
                            'warning' => 'Warning',
                            'danger' => 'Fanger',
                            'light' => 'Light',
                            'dark' => 'Dark',
                        ),
                        'default_value' => 'primary',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_6433475901288',
                        'label' => 'Text column padding',
                        'name' => 'text_column_padding',
                        'aria-label' => '',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 2,
                        'min' => 0,
                        'max' => 4,
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_643348daa83a1',
                        'label' => 'Text column minimum height',
                        'name' => 'text_column_minimum_height',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 200,
                        'min' => 200,
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_64334d109d404',
                        'label' => 'Title column background color',
                        'name' => 'title_column_background_color',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'primary' => 'Theme primary',
                            'primary-dark' => 'Theme primary dark',
                            'primary-darker' => 'Theme primary darker',
                            'secondary' => 'Theme secondary',
                            'success' => 'Success',
                            'info' => 'Info',
                            'warning' => 'Warning',
                            'danger' => 'Fanger',
                            'light' => 'Light',
                            'dark' => 'Dark',
                        ),
                        'default_value' => 'primary',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_643347800293f',
                        'label' => 'Title column padding',
                        'name' => 'title_column_padding',
                        'aria-label' => '',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 2,
                        'min' => 0,
                        'max' => 4,
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6433490ca83a2',
                        'label' => 'Title column minimum height',
                        'name' => 'title_column_minimum_height',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 200,
                        'min' => 200,
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_643334eb10302',
                        'label' => 'Show banner',
                        'name' => 'show_banner',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 1,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_6432f42344834',
                        'label' => 'Post per page',
                        'name' => 'post_per_page',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 5,
                        'min' => -1,
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6432f45f44835',
                        'label' => 'Order',
                        'name' => 'order',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'desc' => 'Desc',
                            'asc' => 'Asc',
                        ),
                        'default_value' => 'desc',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'block',
                            'operator' => '==',
                            'value' => 'acf/all-conferences',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));

            acf_add_local_field_group(array(
                'key' => 'group_6430c4ea91e97',
                'title' => 'Conference',
                'fields' => array(
                    array(
                        'key' => 'field_6430c50637310',
                        'label' => 'Description',
                        'name' => 'description',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_6430c51f37311',
                        'label' => 'Location',
                        'name' => 'location',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6430c53637312',
                        'label' => 'Date',
                        'name' => 'start_date',
                        'aria-label' => '',
                        'type' => 'date_picker',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'm/d/Y',
                        'return_format' => 'm/d/Y',
                        'first_day' => 0,
                    ),
                    array(
                        'key' => 'field_643237e593d94',
                        'label' => 'End date',
                        'name' => 'end_date',
                        'aria-label' => '',
                        'type' => 'date_picker',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'm/d/Y',
                        'return_format' => 'm/d/Y',
                        'first_day' => 0,
                    ),
                    array(
                        'key' => 'field_64320ff2e6da9',
                        'label' => 'Banner',
                        'name' => 'banner',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'library' => 'all',
                        'min_width' => 900,
                        'min_height' => 400,
                        'min_size' => '',
                        'max_width' => 1500,
                        'max_height' => 600,
                        'max_size' => '',
                        'mime_types' => '',
                        'preview_size' => 'medium',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'conference',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));

            acf_add_local_field_group(array(
                'key' => 'group_6431ee07cb12c',
                'title' => 'Options',
                'fields' => array(
                    array(
                        'key' => 'field_6431ee083ddcb',
                        'label' => 'Page description',
                        'name' => 'page_description',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => 500,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_6431f8bb519b1',
                        'label' => 'Contact email',
                        'name' => 'contact_email',
                        'aria-label' => '',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6431f8d1519b2',
                        'label' => 'Main branch',
                        'name' => 'main_branch',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'theme-options',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));

            acf_add_local_field_group(array(
                'key' => 'group_6430bc3da24ac',
                'title' => 'Speaker',
                'fields' => array(
                    array(
                        'key' => 'field_6430bcbe33160',
                        'label' => 'Email',
                        'name' => 'email',
                        'aria-label' => '',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6430be1333161',
                        'label' => 'Expertise',
                        'name' => 'expertise',
                        'aria-label' => '',
                        'type' => 'taxonomy',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'taxonomy' => 'expertise',
                        'add_term' => 1,
                        'save_terms' => 1,
                        'load_terms' => 0,
                        'return_format' => 'id',
                        'field_type' => 'multi_select',
                        'allow_null' => 0,
                        'multiple' => 0,
                    ),
                    array(
                        'key' => 'field_6430bed392d6c',
                        'label' => 'Photo',
                        'name' => 'photo',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'library' => 'all',
                        'min_width' => 100,
                        'min_height' => 100,
                        'min_size' => '',
                        'max_width' => 960,
                        'max_height' => 960,
                        'max_size' => '',
                        'mime_types' => '',
                        'preview_size' => 'medium',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'speakers',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'acf_after_title',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));

            acf_add_local_field_group(array(
                'key' => 'group_6430c5c1c0c66',
                'title' => 'Talk',
                'fields' => array(
                    array(
                        'key' => 'field_6430c5e132b74',
                        'label' => 'Time',
                        'name' => 'time',
                        'aria-label' => '',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'H:i:s',
                        'return_format' => 'H:i:s',
                    ),
                    array(
                        'key' => 'field_6430c607b0cc4',
                        'label' => 'Speakers',
                        'name' => 'speakers',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'speakers',
                        ),
                        'taxonomy' => '',
                        'return_format' => 'object',
                        'multiple' => 1,
                        'allow_null' => 0,
                        'ui' => 1,
                    ),
                    array(
                        'key' => 'field_6430c8f1d61bf',
                        'label' => 'Conference',
                        'name' => 'conference',
                        'aria-label' => '',
                        'type' => 'relationship',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'conference',
                        ),
                        'taxonomy' => '',
                        'filters' => array(
                            0 => 'post_type',
                        ),
                        'return_format' => 'object',
                        'min' => '',
                        'max' => '',
                        'elements' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'talk',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));
        }
    }
}
